services:
  superset:
    build: .
    container_name: superset_app
    restart: always
    ports:
      - '8078:8088'
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - ./volumes/superset_home:/app/superset_home
      - /dev/shm:/dev/shm
    environment:
      - SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
    networks:
      - superset_network

  superset-worker:
    build: .
    container_name: superset_worker
    restart: always
    shm_size: '1gb'
    command:
      [
        'celery',
        '--app',
        'superset.tasks.celery_app:app',
        'worker',
        '--pool=prefork',
      ]
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - ./volumes/superset_home:/app/superset_home
    environment:
      - SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
    networks:
      - superset_network

networks:
  superset_network:
    external: true
